dynamic_forms/contact/urls.py
# from django
from django.conf.urls.defaults import *

urlpatterns = patterns('contact.views',
    url(r'^$', 'list_contacts', name="list_contacts"),
    url(r'^(?P<pk>[\d]+)$', 'show_contact', name="show_contact"),
    url(r'^add/$', 'add_contact', name="add_contact"),
    url(r'^add/(?P<type_form>[\w]+)/$', 'add_contact', name="add_contact"),
)

dynamic_forms/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^dynamic_forms/', include('dynamic_forms.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # (r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # (r'^admin/', include(admin.site.urls)),
    url(r"^", include("contact.urls",
                     namespace="contact",
                     app_name="contact")),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(?P<path>.*)$',
            'django.views.static.serve',
            {'document_root': settings.MEDIA_ROOT}
        ),
    )

dynamic_forms/contact/models.py
from django.db import models


class Contact(models.Model):
    """
    Model for Base form
    NB: Would be better to use the Django User model
    """

    GENDER_CHOICE = (
        (True, "Male"),
        (False, "Female"),
    )

    name = models.CharField("full name", max_length=30, unique=True,
        help_text="Required. 30 characters or fewer. Letters, numbers "
            "and @/./+/-/_ characters",
    )
    email = models.EmailField('e-mail address', blank=True)
    phone = models.CharField('phone number', max_length=12 ,blank=True)
    sex = models.BooleanField(
        'are you a man ?',
        default=True,
        choices=GENDER_CHOICE
    )

    # Special fields
    birthday = models.CharField(blank=True, max_length=10)
    image = models.FileField(
        'Upload an Image',
        upload_to='img/contact',
        blank=True,
        null=True
    )

    def __unicode__(self):
        return self.name

dynamic_forms/contact/forms.py
'''
Only one form would be enough, with an argument given in the __init__
to delete the correct field.
'''

# from django
from django import forms

# from app
from models import Contact


class ContactForm(forms.ModelForm):
    """ModelForm for the Contact model"""

    class Meta:
        model = Contact


class ContactFormWithBirthday(ContactForm):
    """ContactForm with a birthday field"""

    class Meta(ContactForm.Meta):
        exclude = ('image', )


class ContactFormWithImage(ContactForm):
    """ContactForm with an upload image field"""

    class Meta(ContactForm.Meta):
        exclude = ('birthday', )

dynamic_forms/contact/views.py
# from django
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template import RequestContext

# from app
from forms import ContactFormWithBirthday
from forms import ContactFormWithImage
from models import Contact


def list_contacts(request):
    """Return the list of registered users"""

    contacts = Contact.objects.all()
    return render_to_response(
        "contact/list_contacts.html",
        locals(),
        context_instance=RequestContext(request),
    )


def add_contact(request, type_form=None):
    """
    If type_form not specified, ask to choose the type of form.
    Else, display the form.
    """

    if type_form == "birthday":
        contactform = ContactFormWithBirthday()
    elif type_form == "image":
        contactform = ContactFormWithImage()

    if request.method == "POST":
        """We try to save the new contact"""
        if "birthday" in request.POST:
            contactform = ContactFormWithBirthday(request.POST)
        elif "image" in request.POST:
            contactform = ContactFormWithImage(request.POST, request.FILES)
        if contactform.is_valid():
            contactform.save()
            return HttpResponseRedirect(reverse("contact:list_contacts"))
        else:
            warnings = "There was a problem with the submitted form. "\
                "Please see the error messages next to the affected"\
                " fields."

    # Variable to avoid the extends "base.html" in the template if ajax
    base_template = "base_ajax.html" if request.is_ajax() else "base.html"

    return render_to_response(
        "contact/add_contact.html",
        locals(),
        context_instance=RequestContext(request),
    )


def show_contact(request, pk):
    """Give details for one contact"""

    contact = Contact.objects.get(id=pk)
    base_template = "base_ajax.html" if request.is_ajax() else "base.html"

    return render_to_response(
        "contact/show_contact.html",
        locals(),
        context_instance=RequestContext(request),
    )

dynamic_forms/contact/templates/contact/add_contact.html
{% extends base_template %}


{% block title %}: Add user{% endblock %}

{% block header %}
    {% if warnings %}
        <strong>{{ warnings }}</strong>
    {% endif %}
{% endblock %}

{% block content %}
    {% if not contactform %}
        <h2>What kind of contact do you want to create ?</h2>

        <ul>
            <li><a href='{% url contact:add_contact type_form="birthday" %}'>A contact with a Birthday</a></li>
            <li><a href='{% url contact:add_contact type_form="image" %}'>A contact with an Image</a></li>
        </ul>
    {% else %}
        <form action="{% url contact:add_contact %}" method="post">
            {% csrf_token %}
             <table>
                {% for field in contactform %}
                <tr>
                    <th>
                        {{ field.label_tag }}
                        {% if field.field.required %} *{% endif %}
                    </th>
                    <td>
                        {{ field.errors }}
                        {{ field }}
                        {{ field.help_text }}
                    </td>
                </tr>
                {% endfor %}
             </table>
            <p><input type="submit" value="Submit" /></p>
        </form>
    {% endif %}
{% endblock %}

dynamic_forms/contact/templates/contact/list_contacts.html
{% extends "base.html" %}


{% block title %}: List users{% endblock %}


{% block content %}
    <h1>List users</h1>

    {% if contacts %}
    <div id="list_contacts">
    <!-- list of users -->
        <ul>
            {% for contact in contacts %}
            <li>
                <strong>{{ contact.name}}</strong>
                (<a href="{% url contact:show_contact pk=contact.pk %}">see details</a>)
            </li>
            {% endfor %}
        </ul>
    </div>
    <div id="show_contact">
    <!-- details for one user -->
    </div>
    {% else %}
        <p>Sorry there is currently no contact</p>
    {% endif %}


    <hr>
    <a id="link_form" href="{% url contact:add_contact %}">Add a new contact</a>
    <div id="add_contact"></div>
    <div id="contact_form"></div>
{% endblock %}


{% block jquery_ready %}
    var links_to_ajax = function(links, container, sublinks) {
        $(links).each(function() {
            $(this).click(function() {
                $(container).load($(this).attr("href"), function () {
                    if (sublinks != undefined) {
                        links_to_ajax(sublinks, "#contact_form");
                    }
                });
                return false;
            });
        });
    }
    links_to_ajax("#list_contacts a", "#show_contact")
    links_to_ajax("#link_form", "#add_contact", "#add_contact a")

    /*
    $("#link_form").click(function() {
        $("#add_contact").load($(this).attr("href"), function () {
            $("a").each(function() {
                $(this).click(function() {
                    $("#contact_form").load($(this).attr("href"));
                    return false;
                });
            });
        });
        return false;
    });*/
{% endblock %}

dynamic_forms/contact/templates/contact/show_contact.html
{% extends base_template %}


{% block title %}: {{ contact }}{% endblock %}


{% block header %}
    Contact : {{ contact }}
{% endblock %}

{% block content %}
    <ul>
        <li><span>E-mail</span>: {{ contact.email }}</li>
        <li><span>Phone</span>: {{ contact.phone }}</li>
        <li><span>Sex</span>: {{ contact.get_sex_display }}</li>
        {% if contact.image %}
            <li><span>Image</span>: <img src="{{ contact.image }}" /></li>
        {% else %}
            <li><span>Birthday</span>: {{ contact.birthday }}</li>
        {% endif %}
    </ul>
{% endblock %}

dynamic_forms/templates/base.html
<!doctype html>  


<head>
  <title>
      Dynamic Forms {% block title %}{% endblock %}
  </title>

  <meta charset="utf-8">
  <!-- Force latest IE rendering engine (even in intranet) & Chrome Frame -->
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <meta name="description" content="Django Exercice about dynamic forms">
  <meta name="author" content="Adrien Lemaire">
  <link rel="stylesheet" href="{{ MEDIA_URL }}css/style.css" />
</head>


<body>
    <header>
        {% block header %}{% endblock %}
    </header>
    
    <div id="content">
        {% block content %}{% endblock %}
    </div>
    
    <footer>
        {% block footer %}{% endblock %}

    </footer>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.4.4/jquery.min.js">
    </script>
    <script>
        !window.jQuery && document.write(unescape('%3Cscript src="{{ MEDIA_URL }}js/jquery-1.4.4.js"%3E%3C/script%3E')
        )
    </script>
    <script>
        $(document).ready(function(){
            {% block jquery_ready %}{% endblock %}
        });
    </script>
      

</body>
</html>

dynamic_forms/templates/base_ajax.html
{% block content %}
{% endblock %}